language: cpp

branches:
  only:
   - master
   - /^devel_.*$/
   - ppc64le

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - which $CXX
  - which $CC

before_script:
  - autoreconf -fi
  - ./configure

script:
  - make

matrix:
  include:
    - compiler: gcc
      arch: amd64
    - compiler: gcc
      arch: ppc64le
    - compiler: gcc
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: GCC_VERSION=5
    - compiler: gcc
      arch: ppc64le
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: GCC_VERSION=5
    - compiler: gcc
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: GCC_VERSION=6
    - compiler: gcc
      arch: ppc64le
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: GCC_VERSION=6
